version: "3.3"

services:
  postgresql:
    container_name: parkwhere-app_postgresql
    image: postgres:alpine
    ports:
      - "1679:5432"
    environment:
      POSTGRES_USER: parkwheredev
      POSTGRES_PASSWORD: parkwheredev
      POSTGRES_DB: parkwhere
    volumes:
      - ./src/main/resources/database/create_table.sql:/docker-entrypoint-initdb.d/s1_create_table.sql
      - ./src/main/resources/database/bootstrap_test_db.sql:/docker-entrypoint-initdb.d/s2_bootstrap_test_db.sql
    networks:
      - parkwhere-network
networks:
  parkwhere-network:
    driver: bridge
