# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Gradle Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for scripts/prepare_test_db.sh
      run: chmod +x ./scripts/prepare_test_db.sh
    - name: Run script to prepare test db
      run: ./scripts/prepare_test_db.sh
    - name: Build with Gradle
      run: ./gradlew build
